import "./styles/globals.css";
import { Open_Sans } from 'next/font/google'
import Header from "./components/header.js";

const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Overview - UC Berkeley Fee Transparency",
  description: "Generated by Jaysa :)",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={openSans.className}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
